apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  labels:
    app: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: my-app
          image: reethu2/java:v7
          ports:
            - containerPort: 8082
          
