apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  labels:
    app: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: my-app
          image: reethu2/java:v6
          ports:
            - containerPort: 8082
          
