apiVersion: v1
kind: Service
metadata:
  name: my-app-svc-blue
  annotations:
    harness.io/stage-service: "true"
spec:
  type: LoadBalancer
  selector:
    app: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
