apiVersion: v1
kind: Service
metadata:
  name: my-app-svc-green
  annotations:
    harness.io/stage-service: "true"
spec:
  type: LoadBalancer
  selector:
    app: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
