apiVersion: v1
kind: Service
metadata:
  name: my-app-svc-green
  annotations:
    harness.io/primary-service: "true"
    #cloud.google.com/neg: '{"ingress": true}'*/
spec:
  type: LoadBalancer
  selector:
    app: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
